gui: Add missing signal.h include
Fixes build error such as:

src/gui/src/MainWindow.cpp:843:9: error: use of undeclared identifier
'kill'

Note that kill is from Posix, not C++, so csignal cannot be used.